spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: ${PORT}


jwt:
  secret:
    key: ${JWT_SECRET_KEY}

toss:
  secret-key: ${TOSS_SECRET_KEY}
  client-key: ${TOSS_CLIENT_KEY}

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
    channel: ${DISCORD_CHANNEL_ID}